spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/library
    username: postgres
    password: postgres
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/library
    user: postgres
    password: postgres
